name: docker-build
on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**/*
      - .github/workflows/docker-build.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # refs: https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (backend)
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer/
          file: .devcontainer//Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/sfml:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/sfml:latest
          cache-to: type=inline
